version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${SQLPASS}
      MYSQL_DATABASE: ${SQLDB}
      MYSQL_USER: ${SQLUSER}
    ports:
      - '3306:3306'

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SQLPASS: ${SQLPASS}
      SQLDB: ${SQLDB}
      SQLUSER: ${SQLUSER}
      SQLHOST: db
volumes:
  db_data: